name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Arquitetura e Estado
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.6.2

  # Utilitários
  equatable: ^2.0.7
  google_fonts: ^6.3.3
  cupertino_icons: ^1.0.8

  # Storage (Nota: GetStorage funciona bem sem o GetX Framework)
  get_storage: ^2.1.1
  dynamic_color: ^1.8.1

  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Windows Installer
  msix: ^3.16.12

  # Ferramentas de Geração de Código (Versões Compatíveis)
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0

# --- SEÇÃO DO FLUTTER (Atenção à indentação aqui) ---
flutter:
  uses-material-design: true

  # "assets" deve ter 2 espaços para estar DENTRO de "flutter"
  assets:
    - assets/images/logo.png

# --- CONFIGURAÇÕES DE PACOTES EXTERNOS (Ficam na raiz, sem recuo) ---

# Configuração do MSIX (fica no mesmo nível do 'flutter:', encostado na margem esquerda)
msix_config:
  display_name: Windows App
  publisher_display_name: Dionatan
  identity_name: com.dionatan.meuapp
  msix_version: 1.0.0.0
  logo_path: assets/images/logo.png
  capabilities: internetClient